---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Bind at ansible-mgn
    yum: 
      name: bind 
      state: latest
    when: ansible_connection == "local"
  - name: Edit nameserver listen IP address
    lineinfile:
      path: /etc/named.conf
      regexp: 'listen-on port 53 { 127.0.0.1; };'
      line: '        listen-on port 53 { 127.0.0.1; 192.168.100.11;};'
      backup: yes
    when: ansible_connection == 'local'
  - name: Edit nameserver allowe query
    lineinfile:
      path: /etc/named.conf
      regexp: 'allow-query     { localhost; };'
      line: 'allow-query     { any; };'
      backup: yes
    when: ansible_connection == 'local'
  - name: Include path
    lineinfile:
      path: /etc/named.conf
      line: 'include "/etc/named/named.conf.local";'
    when: ansible_connection == 'local'
  - name: Create Zones directory
    file:
      path: /etc/named/zones
      state: directory
      mode: "0755"
    when: ansible_connection == 'local'
  - name: Copy template zone
    template:
      src: '{{item.source}}'
      dest: '{{item.destination}}'
      owner: root
      group: root
      mode: "0755"
    loop:
    - { source: 'template/db.mynet-062.com.j2', destination: '/etc/named/zones/db.mynet-062.com'}
    - { source: 'template/db.192.168.100.j2', destination: '/etc/named/zones/db.192.168.100'}
    when: ansible_connection == 'local'
  - name: Copy template named.conf
    template:
      src: 'template/named.conf.local.j2'
      dest: '/etc/named/named.conf.local'
    when: ansible_connection == 'local'
  - name: started named
    service:
      name: named
      state: started
    when: ansible_connection == 'local'
  - name: Install firewalld
    yum: 
      name: firewalld 
      state: latest
    when: ansible_connection == 'local'
  - name: Start firewalld
    service: 
      name: firewalld
      state: started
    when: ansible_connection == 'local'  
  - name: Open firewall
    firewalld: 
      port: '{{ item }}' 
      permanent: yes 
      state: enabled
    loop:
    - "53/udp"
    - "53/tcp"   
    when: ansible_connection == 'local'
  - name: Restart firewalld
    service: 
      name: firewalld 
      state: restarted
    when: ansible_connection == 'local'  
  - name: Copy template resolve
    template:
      src: 'template/resolv.conf.j2'
      dest: '/etc/resolv.conf'  
  - name: install bind-util
    yum:
      name: bind-utils
      state: latest
  - name: check result
    command: nslookup ansible-mgn.mynet-062.com
    register: myoutput
  - debug: msg="{{ myoutput.stdout }}"

